### ISSUE TITLE
ParsecVDD cannot be run without monitors at cold start

### ISSUE THREAD

**Issue by lancoyan** [ClassicOldSong/Widecar#3]
When comes back from shutdown , any autostart of parsecvdd will fail. Then widecar cannot add new virtual dispay. I found a cli version of parsec vdd. Could widecar use cli way to add virtual display without any physical monitor at cold start as the parsec vdd gui cannot be running.

**Comment by lancoyan** [comment]
Now i use a adapter to cheat as monitor when cold start, all things with widecar works excellent. But if could get off that adapter, the workflow will be more smoother ~~ 😍

**Comment by lancoyan** [comment]
https://github.com/nomi-san/parsec-vdd/issues/13

It seems they are deving official cli supports

**Comment by lancoyan** [comment]
Third party cli support I mentioned: https://github.com/HaliComing/parsec-vdd-cli

still works in 0.45

**Comment by ClassicOldSong** [comment]
Here's a project implements a auto connected display but there it could introduce user logic conflicts: it's always creating a virtual display on its own, which can't be managed by Widecar but you might want to stream the virtual display it created with resolution and frame rate matching, which isn't very doable at the moment.

https://github.com/timminator/ParsecVDA-Always-Connected

Another problem is from the graphics card driver side: on some devices, without a physically connected display, the driver won't release its power limit. So a dummy plug is by far the best solution for a headless setup.

You can configure the dummy plug to "disconnected" in Windows settings after you started streaming with Widecar and Windows will remember the state so you won't need to configure it again the second time you start streaming.

**Comment by ClassicOldSong** [comment]
If none of the issues you mentioned are your concern, the only thing you need is a program to ping the driver constantly. You can try compile the demo https://github.com/nomi-san/parsec-vdd/blob/main/core/vdd-demo.cc and run it at startup.

**Comment by lancoyan** [comment]
Thank you very much for share [ParsecVDA-Always-Connected](https://github.com/timminator/ParsecVDA-Always-Connected). It really solves my biggest problem. Now with the default vitural display always connected, the parsecVDD app finally could autostart at cold start. It seems that default display make the graphic card work and help parsecVDD app.

By the way, your readme helps a lot. Especially the usage of MultiMonitorTool.
I wrote a rule "C:\MultiMonitorTool.exe /disable \\.\DISPLAY10", since the always connected vdd is always display10 on my pc. The rule has been made as a shortcuts on my startmenu and sunshine desktop app detached command as you recommend in readme. But sometimes it will disable the wrong display which made by widecar. I don't figure out wether it's delay time not enough. Of course the windows could also remember the vdd disable state, so I finnaly delete the rule from sunshine detached rule.

PS: At first time, user should change the default option about "Options - Copy/setmonitors command mode - use  \\.\DISPLAYx as name", the command in widecar readme could work.

Although ParsecVDA-Always-Connected can't be managed by Widecar, as you recommended, MultiMonitorTool should be always work with widecar as a whole.

**Comment by lancoyan** [comment]
After more test, pvdd always-connected service has confict with widecar when remove the display. As soon as widecar remove the display, the service of always-connected will made double displays.

So base on the same methods, I installed idds(hdr version) driver to light up cold start. And make a shortcuts by MultiMonitorTool to always disable it when any widecar plug in.

shortcuts: C:\MultiMonitorTool.exe /disable MONITOR\LNX0000\{4d36e96e-e325-11ce-bfc1-08002be10318}\0022

**Comment by ClassicOldSong** [comment]
Widecar is not intended to work on headless systems. It's more of a hack than a dedicated solution. The headless situation might be handled in the future with [my fork of Sunshine](https://github.com/ClassicOldSong/Apollo)

**Comment by ClassicOldSong** [comment]
Hey, I think this issue is now solved perfectly

Try this:
https://github.com/ClassicOldSong/Apollo/releases

Enable "Headless Mode" in Audio/Video configuration and you're good to go!
