### ISSUE TITLE
Turn off all monitors

### ISSUE THREAD

**Issue by Gulivertx** [ClassicOldSong/Widecar#7]
Hello,
Great project and works great with my configuration. 
just thinking if it could be possible to turn off all real monitors before to use the virtual one?

Also is there a way to have hdr turn on off according clients configuration?

regards

**Comment by ClassicOldSong** [comment]
This project is dead. Use Apollo instead.

https://github.com/ClassicOldSong/Apollo/issues/26

**Comment by ClassicOldSong** [comment]
Follow HDR config on client is just added: https://github.com/ClassicOldSong/Apollo/releases/tag/v0.1.3-alpha.2
