### ISSUE TITLE
Gamepad response error

### ISSUE THREAD

**Issue by yybfrank** [ClassicOldSong/Widecar#8]
I opened two sunshine instance and run Moonlight on two computers at the same time. Only the gamepad of the first computer responded, and the gamepad of the second computer did not respond. Moreover, the gamepad of the first computer controls the game of the second computer.

**Comment by ClassicOldSong** [comment]
Widecar has been abandoned. No support will be provided moreover. Please use Apollo instead.

This project and Apollo's instructions for starting multiple instances aren't meant for playing two games simultaneously, but for creating more virtual displays for one computer. That means, the gamepad from the second instance will act like P2 when you plug two game pads into one computer, and usually only the active window (which will be the game starting later) will get input from gamepads, that could explain why "the first gamepad controls the second computer". This is not a software for "free" multi account computer.

**Comment by yybfrank** [comment]
thank you for your reply,but I want to run multiple sunshine instances and playing two game at the same time,how to implement it? is Apollo support that?
